### ISSUE TITLE
大佬，windows第二步报错

### ISSUE THREAD

**Issue by lhbdhr** [Alozxy/trav#2]
第一步成功获取到公网IP和端口。
TCP ping 了一下全绿。
```
.\trav -r 13954 -o .\external.port -s stun.mixvoip.com:3478
```
但是第二部端口会重复
```
.\trav-bittorrent -w .\external.port -c qbittorrent -u admin -p password -s 127.0.0.1:8080

提示是：
127.0.0.1:8080
2023/03/29 19:38:15 modifying listening port...
2023/03/29 19:38:15 login successfully
2023/03/29 19:38:15 set preferences successfully
2023/03/29 19:38:15 modifying ipv4 iptables redirect rule...
panic: listen udp 0.0.0.0:12345: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 1 [running]:
main.set_rule_v4(0x3682)
        /github/workspace/ipt_windows.go:36 +0x396
main.main()
        /github/workspace/main.go:97 +0xb3d
```

第一步和第二步要使用不同的端口号吗？

**Comment by lhbdhr** [comment]
光猫桥接到小米路由器拨号，
用的小米官方固件，不确定是否有IPV4传入防火墙，是不是因为这个原因呀？
要怎么测试是不是这个因素呢？

**Comment by Alozxy** [comment]
> 光猫桥接到小米路由器拨号，然后开启DMZ到windows电脑， 用的小米官方固件，不确定是否有IPV4传入防火墙，是不是因为这个原因呀？ 电脑的防火墙我确认我放行了。 要怎么测试是不是这个因素呢？

是的，要把-l参数对应的端口的入站防火墙打开
不过我没有小米路由器，不知道能不能单独打开一个端口，你可以先把防火墙关了试试看

**Comment by lhbdhr** [comment]
/(ㄒoㄒ)/~~

小米没法设置IPV4的防火墙开关，只有IPV6的防火墙开关。

我现在都不知道路由器自带的防火墙是开着的还是关着的。
有没有什么工具能测一下，到底有没有防火墙呀。

**Comment by Alozxy** [comment]
> 我刚才想着试试别的打洞工具测一下能不能成功， 结果成功了，用的这个 https://github.com/MikeWang000000/Natter 公网IP+端口，开启了web服务，可以访问。 看来不是防火墙的问题。

**Comment by Alozxy** [comment]
> 我刚才想着试试别的打洞工具测一下能不能成功， 结果成功了，用的这个 https://github.com/MikeWang000000/Natter 公网IP+端口，开启了web服务，可以访问。 看来不是防火墙的问题。

很奇怪，原理应该是一样的

不过问题解决了就好

**Comment by lhbdhr** [comment]
现在0.4.2版本有连接传入的时候powershell会有log提示吗？
我发现我PT网站后台的端口已经变成了公网打洞的端口，不是我PT客户端设置的端口，
竟然还有上传，有人用ipv4连接我，虽然tcp ping 全红。
这是不是已经成功了啊？
